import type { Question } from "./questions";

// Each topic: 6 levels (age 5 → GCSE), 3-4 questions per level
export const EXPANDED_ENGLISH: Record<string, Question[][]> = {
  "Reading": [
    [
      { q: "What is the start of a book called?", options: ["End", "Middle", "Beginning", "Side"], answer: "Beginning" },
      { q: "A person in a story is called a...", options: ["Writer", "Character", "Reader", "Book"], answer: "Character" },
      { q: "What do we call the person reading?", options: ["Writer", "Reader", "Speaker", "Listener"], answer: "Reader" },
      { q: "A book with pictures is called a...", options: ["Novel", "Picture book", "Newspaper", "Letter"], answer: "Picture book" },
    ],
    [
      { q: "What does a 'title' tell you?", options: ["Nothing", "The book's name", "The end", "Who wrote it"], answer: "The book's name" },
      { q: "A book of facts is called...", options: ["Fiction", "Non-fiction", "Poetry", "Drama"], answer: "Non-fiction" },
      { q: "Who writes a book?", options: ["Reader", "Author", "Printer", "Seller"], answer: "Author" },
      { q: "Pictures in a book are called...", options: ["Words", "Covers", "Illustrations", "Titles"], answer: "Illustrations" },
    ],
    [
      { q: "What is the main character called?", options: ["Villain", "Protagonist", "Narrator", "Author"], answer: "Protagonist" },
      { q: "What does 'fiction' mean?", options: ["True stories", "Made up stories", "News", "Poetry"], answer: "Made up stories" },
      { q: "The 'plot' is the...", options: ["Cover", "Story events", "Author's name", "Book size"], answer: "Story events" },
      { q: "A 'villain' is usually...", options: ["The hero", "The bad character", "The narrator", "The author"], answer: "The bad character" },
    ],
    [
      { q: "What is a 'setting' in a story?", options: ["Characters", "Plot", "Where/when it happens", "The ending"], answer: "Where/when it happens" },
      { q: "What is a 'theme'?", options: ["Story's main idea", "Title", "Author's name", "Page number"], answer: "Story's main idea" },
      { q: "'Point of view' means...", options: ["A place", "Who tells the story", "A character", "The ending"], answer: "Who tells the story" },
      { q: "A 'genre' is...", options: ["A character", "Type of story", "The setting", "The plot"], answer: "Type of story" },
    ],
    [
      { q: "What is an autobiography?", options: ["A fiction book", "Your own life story", "A poem", "A play"], answer: "Your own life story" },
      { q: "A 'biography' is written about...", options: ["Yourself", "Someone else's life", "Fictional characters", "Fantasy"], answer: "Someone else's life" },
      { q: "What does 'foreshadowing' mean?", options: ["Dark places", "Hints at future events", "A type of shadow", "The ending"], answer: "Hints at future events" },
      { q: "What is 'symbolism'?", options: ["Using pictures", "Objects representing ideas", "Bold text", "Bullet points"], answer: "Objects representing ideas" },
    ],
    [
      { q: "What does 'inference' mean?", options: ["Guessing randomly", "Reading aloud", "Working out meaning from clues", "Copying text"], answer: "Working out meaning from clues" },
      { q: "What is the 'tone' of a text?", options: ["How loud it is", "The feeling/mood it creates", "The font used", "How long it is"], answer: "The feeling/mood it creates" },
      { q: "'Dramatic irony' is when...", options: ["Readers know more than characters", "The plot twists", "It rhymes", "The author dies"], answer: "Readers know more than characters" },
      { q: "A 'motif' is a...", options: ["Main character", "Recurring element or idea", "Chapter title", "Plot twist"], answer: "Recurring element or idea" },
    ],
  ],
  "Spelling": [
    [
      { q: "Which is correct?", options: ["kat", "cat", "katt", "catt"], answer: "cat" },
      { q: "Which is correct?", options: ["dogg", "dog", "doge", "dawg"], answer: "dog" },
      { q: "Which is correct?", options: ["hows", "house", "hous", "houss"], answer: "house" },
      { q: "Which is correct?", options: ["mum", "muhm", "mumm", "mumee"], answer: "mum" },
    ],
    [
      { q: "Which is correct?", options: ["frend", "freind", "friend", "frennd"], answer: "friend" },
      { q: "Which is correct?", options: ["skool", "school", "shool", "skule"], answer: "school" },
      { q: "Which is correct?", options: ["peeple", "peple", "people", "peopel"], answer: "people" },
      { q: "Which is correct?", options: ["becuz", "becuase", "because", "becase"], answer: "because" },
    ],
    [
      { q: "Which is correct?", options: ["wen", "when", "whenn", "wehn"], answer: "when" },
      { q: "Which is correct?", options: ["beautifull", "beautiful", "beautful", "beutiful"], answer: "beautiful" },
      { q: "Which is correct?", options: ["believ", "beleive", "believe", "beleve"], answer: "believe" },
      { q: "Which is correct?", options: ["ther", "their", "thier", "there's"], answer: "their" },
    ],
    [
      { q: "Which is correct?", options: ["diffrent", "diferent", "different", "differant"], answer: "different" },
      { q: "Which is correct?", options: ["favourite", "faverite", "favourit", "favrite"], answer: "favourite" },
      { q: "Which is correct?", options: ["seperate", "separete", "separate", "separat"], answer: "separate" },
      { q: "Which is correct?", options: ["definately", "definitely", "definetly", "defanitly"], answer: "definitely" },
    ],
    [
      { q: "Which is correct?", options: ["necessary", "neccessary", "necesary", "neccesary"], answer: "necessary" },
      { q: "Which is correct?", options: ["rhythm", "rythm", "rithym", "ryhthm"], answer: "rhythm" },
      { q: "Which is correct?", options: ["embarass", "embarras", "embarrass", "embarras"], answer: "embarrass" },
      { q: "Which is correct?", options: ["acheive", "achieve", "acheeve", "achive"], answer: "achieve" },
    ],
    [
      { q: "Which is correct?", options: ["accomodate", "accommodate", "acommodate", "acomodate"], answer: "accommodate" },
      { q: "Which is correct?", options: ["occassion", "ocassion", "occasion", "ocasion"], answer: "occasion" },
      { q: "Which is correct?", options: ["consciense", "conscience", "concience", "consience"], answer: "conscience" },
      { q: "Which is correct?", options: ["questionnaire", "questionaire", "questionnair", "questionare"], answer: "questionnaire" },
    ],
  ],
  "Grammar": [
    [
      { q: "Which is a naming word?", options: ["Run", "Cat", "Quickly", "Happy"], answer: "Cat" },
      { q: "Which is an action?", options: ["Apple", "Table", "Jump", "Red"], answer: "Jump" },
      { q: "Which is a describing word?", options: ["Eat", "Big", "Chair", "Fast"], answer: "Big" },
      { q: "Which is a name?", options: ["Run", "Sam", "Quick", "Fast"], answer: "Sam" },
    ],
    [
      { q: "Which is a noun?", options: ["Run", "Happy", "Cat", "Quickly"], answer: "Cat" },
      { q: "Which is a verb?", options: ["Beautiful", "Jump", "Table", "Red"], answer: "Jump" },
      { q: "Capital letters start which type of noun?", options: ["Common", "Proper", "Collective", "Plural"], answer: "Proper" },
      { q: "Plural of 'cat' is...", options: ["cats", "cates", "cati", "catz"], answer: "cats" },
    ],
    [
      { q: "What is an adjective?", options: ["Action word", "Describing word", "Naming word", "Joining word"], answer: "Describing word" },
      { q: "Pick the adjective:", options: ["The small cat", "Run fast", "Under the table", "He jumps"], answer: "The small cat" },
      { q: "'The' is what type of word?", options: ["Noun", "Verb", "Article", "Adjective"], answer: "Article" },
      { q: "Plural of 'child'?", options: ["childs", "childrens", "children", "childen"], answer: "children" },
    ],
    [
      { q: "Pick the adverb:", options: ["Fast car", "Run quickly", "Blue sky", "Big house"], answer: "Run quickly" },
      { q: "What is a pronoun?", options: ["A noun replacement", "An action", "A describer", "A question"], answer: "A noun replacement" },
      { q: "Pick the preposition:", options: ["The", "Under", "Jump", "Happy"], answer: "Under" },
      { q: "Past tense of 'go' is...", options: ["goed", "gone", "went", "goes"], answer: "went" },
    ],
    [
      { q: "'Their', 'there' or 'they're': ___ going home", options: ["Their", "There", "They're", "Theyre"], answer: "They're" },
      { q: "Choose the correct: 'She ___ to school daily.'", options: ["go", "goes", "gone", "going"], answer: "goes" },
      { q: "What is a 'conjunction'?", options: ["Linking word", "Noun", "Verb", "Adjective"], answer: "Linking word" },
      { q: "Past perfect of 'eat' is...", options: ["ate", "eaten", "had eaten", "eating"], answer: "had eaten" },
    ],
    [
      { q: "What is a subordinate clause?", options: ["A main sentence", "A dependent part", "A question", "A paragraph"], answer: "A dependent part" },
      { q: "Active or passive: 'The cake was eaten by Sam'", options: ["Active", "Passive", "Neither", "Both"], answer: "Passive" },
      { q: "A 'relative clause' starts with...", options: ["Full stops", "Relative pronouns like 'who', 'which'", "Adjectives", "Nothing"], answer: "Relative pronouns like 'who', 'which'" },
      { q: "What is the 'subjunctive mood'?", options: ["Past tense", "Expressing wishes/hypotheticals", "Questions only", "Commands"], answer: "Expressing wishes/hypotheticals" },
    ],
  ],
  "Punctuation": [
    [
      { q: "Sentences start with a...", options: ["Small letter", "Capital letter", "Number", "Space"], answer: "Capital letter" },
      { q: "Sentences end with a...", options: ["Comma", "Full stop", "Colon", "Dash"], answer: "Full stop" },
      { q: "A question ends with...", options: ["!", "?", ".", ","], answer: "?" },
      { q: "Excitement ends with...", options: ["!", "?", ".", ":"], answer: "!" },
    ],
    [
      { q: "What shows someone is talking?", options: ["Brackets", "Speech marks", "Commas", "Dashes"], answer: "Speech marks" },
      { q: "Commas separate items in a...", options: ["List", "Question", "Title", "Heading"], answer: "List" },
      { q: "'I can't' uses what?", options: ["Comma", "Apostrophe", "Colon", "Dash"], answer: "Apostrophe" },
      { q: "A pause in a sentence uses?", options: ["Comma", "Full stop", "Question mark", "Nothing"], answer: "Comma" },
    ],
    [
      { q: "The dog's bone - apostrophe shows...", options: ["Contraction", "Possession", "Plural", "Nothing"], answer: "Possession" },
      { q: "Direct speech needs...", options: ["No punctuation", "Speech marks", "Only commas", "Capitals only"], answer: "Speech marks" },
      { q: "Brackets ( ) are used to...", options: ["End sentences", "Add extra info", "Start lists", "Ask questions"], answer: "Add extra info" },
      { q: "Where does a full stop go in a sentence?", options: ["Start", "Middle", "End", "Anywhere"], answer: "End" },
    ],
    [
      { q: "When do you use an apostrophe?", options: ["Plurals", "Questions", "Possession/contraction", "Lists"], answer: "Possession/contraction" },
      { q: "Use a comma before 'but' in a...", options: ["Simple sentence", "Compound sentence", "Never", "Always"], answer: "Compound sentence" },
      { q: "Ellipsis (...) shows...", options: ["Excitement", "A pause or omission", "Ending", "A question"], answer: "A pause or omission" },
      { q: "A dash can be used to...", options: ["End sentences", "Add emphasis or interruption", "Ask questions", "Start lists only"], answer: "Add emphasis or interruption" },
    ],
    [
      { q: "A semicolon joins...", options: ["Words", "Letters", "Related clauses", "Paragraphs"], answer: "Related clauses" },
      { q: "Which is correct?", options: ["Its raining", "It's raining", "Its' raining", "Its raining'"], answer: "It's raining" },
      { q: "A colon is used before a...", options: ["Paragraph", "List or explanation", "Full stop", "Question"], answer: "List or explanation" },
      { q: "Hyphens join...", options: ["Sentences", "Words (e.g. well-known)", "Paragraphs", "Nothing"], answer: "Words (e.g. well-known)" },
    ],
    [
      { q: "Parenthesis uses what punctuation?", options: ["Commas, brackets, or dashes", "Only full stops", "Only colons", "Only semicolons"], answer: "Commas, brackets, or dashes" },
      { q: "Which is correct: 'The CEO's decision was final.'", options: ["Correct", "Should be CEOs", "Should be CEO", "Should be CEOs'"], answer: "Correct" },
      { q: "Correct use of semicolon?", options: ["Before 'and'", "Between independent clauses", "At start of sentence", "In titles only"], answer: "Between independent clauses" },
      { q: "The Oxford comma goes...", options: ["Before 'and' in a list", "Never used", "At start of sentence", "Only in questions"], answer: "Before 'and' in a list" },
    ],
  ],
  "Vocabulary": [
    [
      { q: "What does 'big' mean?", options: ["Small", "Large", "Hot", "Fast"], answer: "Large" },
      { q: "The opposite of 'up' is?", options: ["Over", "Down", "Side", "Top"], answer: "Down" },
      { q: "'Happy' means...", options: ["Sad", "Joyful", "Angry", "Tired"], answer: "Joyful" },
      { q: "A 'tiny' thing is...", options: ["Huge", "Medium", "Very small", "Fast"], answer: "Very small" },
    ],
    [
      { q: "What does 'enormous' mean?", options: ["Tiny", "Very big", "Medium", "Fast"], answer: "Very big" },
      { q: "Another word for 'angry' is...", options: ["Happy", "Furious", "Kind", "Quiet"], answer: "Furious" },
      { q: "Opposite of 'cold' is...", options: ["Cool", "Hot", "Warm", "Wet"], answer: "Hot" },
      { q: "'Quick' means...", options: ["Slow", "Heavy", "Fast", "Big"], answer: "Fast" },
    ],
    [
      { q: "A 'synonym' is a word that...", options: ["Rhymes", "Means the same", "Means opposite", "Is foreign"], answer: "Means the same" },
      { q: "What is an 'antonym'?", options: ["Same meaning", "Opposite meaning", "Rhyme", "Long word"], answer: "Opposite meaning" },
      { q: "'Ancient' means...", options: ["Modern", "Very old", "Brand new", "Big"], answer: "Very old" },
      { q: "'Gigantic' means...", options: ["Tiny", "Medium", "Extremely big", "Slow"], answer: "Extremely big" },
    ],
    [
      { q: "What does 'reluctant' mean?", options: ["Eager", "Unwilling", "Fast", "Kind"], answer: "Unwilling" },
      { q: "An antonym of 'brave' is...", options: ["Courageous", "Bold", "Cowardly", "Strong"], answer: "Cowardly" },
      { q: "'Generous' means...", options: ["Stingy", "Giving", "Mean", "Shy"], answer: "Giving" },
      { q: "'Furious' means extremely...", options: ["Tired", "Happy", "Angry", "Sad"], answer: "Angry" },
    ],
    [
      { q: "'Benevolent' means...", options: ["Evil", "Kind-hearted", "Smart", "Lazy"], answer: "Kind-hearted" },
      { q: "'Meticulous' means...", options: ["Careless", "Very careful", "Quick", "Funny"], answer: "Very careful" },
      { q: "What does 'perplexed' mean?", options: ["Confused", "Happy", "Tired", "Fast"], answer: "Confused" },
      { q: "A 'dubious' claim is...", options: ["Certain", "Doubtful", "Proven", "Famous"], answer: "Doubtful" },
    ],
    [
      { q: "'Ubiquitous' means...", options: ["Rare", "Found everywhere", "Invisible", "Old"], answer: "Found everywhere" },
      { q: "'Ephemeral' means...", options: ["Eternal", "Lasting briefly", "Permanent", "Large"], answer: "Lasting briefly" },
      { q: "'Pragmatic' means...", options: ["Idealistic", "Practical/realistic", "Romantic", "Theoretical"], answer: "Practical/realistic" },
      { q: "'Quintessential' means...", options: ["Rare", "Most perfect example", "Fifth one", "Unusual"], answer: "Most perfect example" },
    ],
  ],
  "Creative Writing": [
    [
      { q: "A story has a beginning, middle and...", options: ["Top", "End", "Side", "Bottom"], answer: "End" },
      { q: "Who tells the story?", options: ["Reader", "Narrator", "Teacher", "Book"], answer: "Narrator" },
      { q: "A story about made-up things is...", options: ["True", "Fiction", "News", "A list"], answer: "Fiction" },
      { q: "A story might start with 'Once upon a...'", options: ["Day", "Time", "Year", "Place"], answer: "Time" },
    ],
    [
      { q: "Describing words make writing...", options: ["Boring", "More interesting", "Shorter", "Longer only"], answer: "More interesting" },
      { q: "A 'character' in a story is a...", options: ["Place", "Person or creature", "Time", "Object"], answer: "Person or creature" },
      { q: "A good story has a...", options: ["Problem and solution", "Only facts", "No people", "No action"], answer: "Problem and solution" },
      { q: "The 'setting' tells us...", options: ["Where and when", "Who", "What happened", "The name"], answer: "Where and when" },
    ],
    [
      { q: "A simile uses which words?", options: ["But, however", "Like, as", "And, then", "Because, so"], answer: "Like, as" },
      { q: "'Quiet as a mouse' is a...", options: ["Metaphor", "Simile", "Rhyme", "Fact"], answer: "Simile" },
      { q: "What's a 'cliffhanger'?", options: ["A type of cliff", "A suspenseful ending", "The beginning", "A character"], answer: "A suspenseful ending" },
      { q: "First person uses...", options: ["He/she", "I/me", "You", "They"], answer: "I/me" },
    ],
    [
      { q: "What is a metaphor?", options: ["A comparison using 'like'", "A direct comparison", "A rhyme", "A long sentence"], answer: "A direct comparison" },
      { q: "'Her voice is music' is a...", options: ["Simile", "Metaphor", "Fact", "Question"], answer: "Metaphor" },
      { q: "What is 'dialogue'?", options: ["Description", "Characters speaking", "A setting", "Narration"], answer: "Characters speaking" },
      { q: "What is a 'flashback'?", options: ["End of story", "Returning to past events", "A question", "A setting"], answer: "Returning to past events" },
    ],
    [
      { q: "What is 'alliteration'?", options: ["Rhyming words", "Same starting sounds", "Long words", "Short sentences"], answer: "Same starting sounds" },
      { q: "What is 'personification'?", options: ["Using names", "Giving human traits to non-human things", "Writing in first person", "A type of poem"], answer: "Giving human traits to non-human things" },
      { q: "'Hyperbole' means...", options: ["Understatement", "Exaggeration", "Fact", "A rhyme"], answer: "Exaggeration" },
      { q: "Show, don't tell means...", options: ["Use description to reveal feelings", "Keep secrets", "Never use dialogue", "Write shortest sentences"], answer: "Use description to reveal feelings" },
    ],
    [
      { q: "'Onomatopoeia' means words that...", options: ["Are long", "Sound like their meaning", "Rhyme", "Are foreign"], answer: "Sound like their meaning" },
      { q: "What is a 'narrative hook'?", options: ["A fishing term", "An engaging opening", "The ending", "A character name"], answer: "An engaging opening" },
      { q: "'Pathetic fallacy' is...", options: ["A weak argument", "Weather reflecting mood", "A character flaw", "Bad writing"], answer: "Weather reflecting mood" },
      { q: "What is 'juxtaposition'?", options: ["Contrasting two things side by side", "A rhyme", "A character", "An ending"], answer: "Contrasting two things side by side" },
    ],
  ],
  "Comprehension": [
    [
      { q: "To 'understand' means to...", options: ["Ignore", "Get it", "Write", "Draw"], answer: "Get it" },
      { q: "Reading means...", options: ["Drawing pictures", "Looking at words and understanding", "Only listening", "Nothing"], answer: "Looking at words and understanding" },
      { q: "If you don't know a word, you can...", options: ["Give up", "Ask or look it up", "Skip it forever", "Cry"], answer: "Ask or look it up" },
      { q: "A book's title is usually on the...", options: ["Back", "Cover", "Last page", "Middle"], answer: "Cover" },
    ],
    [
      { q: "The first sentence of a paragraph is often the...", options: ["End", "Main idea", "Question", "Title"], answer: "Main idea" },
      { q: "To find answers, you should read...", options: ["The cover only", "Carefully", "Very fast", "Only pictures"], answer: "Carefully" },
      { q: "Who/what/where/when/why are...", options: ["Answers", "Question words", "Titles", "Names"], answer: "Question words" },
      { q: "Facts are things that are...", options: ["Made up", "True", "Opinions", "Questions"], answer: "True" },
    ],
    [
      { q: "What does 'comprehension' mean?", options: ["Writing", "Understanding", "Speaking", "Drawing"], answer: "Understanding" },
      { q: "A 'summary' is a...", options: ["Long version", "Short overview", "Copy of text", "Question"], answer: "Short overview" },
      { q: "An opinion is...", options: ["Always true", "Someone's belief", "Proven", "A fact"], answer: "Someone's belief" },
      { q: "'Scanning' means reading...", options: ["Every word slowly", "For specific information", "Aloud only", "Backwards"], answer: "For specific information" },
    ],
    [
      { q: "Skimming a text means...", options: ["Reading every word", "Reading quickly for main ideas", "Copying it out", "Ignoring it"], answer: "Reading quickly for main ideas" },
      { q: "What is a 'topic sentence'?", options: ["The last sentence", "The longest sentence", "The main idea sentence", "A question"], answer: "The main idea sentence" },
      { q: "What is 'context' in reading?", options: ["The surrounding info that gives meaning", "The title only", "Punctuation", "Page number"], answer: "The surrounding info that gives meaning" },
      { q: "To 'paraphrase' means to...", options: ["Copy exactly", "Put in your own words", "Ignore", "Translate"], answer: "Put in your own words" },
    ],
    [
      { q: "PEE stands for (in English essays)...", options: ["Point, Evidence, Explain", "Plan, Edit, Evaluate", "Predict, Examine, End", "Practice, Explore, Expand"], answer: "Point, Evidence, Explain" },
      { q: "What does 'evaluate' mean?", options: ["Copy", "Judge the value of", "Ignore", "Summarise only"], answer: "Judge the value of" },
      { q: "A text's 'purpose' is its...", options: ["Length", "Reason for being written", "Title", "Author"], answer: "Reason for being written" },
      { q: "'Bias' in a text means...", options: ["It's true", "It's fair", "It's one-sided", "It has pictures"], answer: "It's one-sided" },
    ],
    [
      { q: "What is 'analysis' in English?", options: ["Retelling", "Close examination of meaning", "Just opinions", "Grammar checking"], answer: "Close examination of meaning" },
      { q: "'Connotation' is a word's...", options: ["Dictionary meaning", "Suggested/emotional meaning", "Pronunciation", "Origin"], answer: "Suggested/emotional meaning" },
      { q: "'Rhetorical devices' are used to...", options: ["Confuse readers", "Persuade and affect readers", "Shorten text", "Add pictures"], answer: "Persuade and affect readers" },
      { q: "What is 'synthesis' in comprehension?", options: ["Copying", "Combining info from multiple sources", "Summarising one text", "Ignoring sources"], answer: "Combining info from multiple sources" },
    ],
  ],
  "Poetry": [
    [
      { q: "A poem is written in...", options: ["Sentences only", "Lines", "Paragraphs", "Chapters"], answer: "Lines" },
      { q: "Cat rhymes with...", options: ["Dog", "Hat", "Fish", "Run"], answer: "Hat" },
      { q: "'Twinkle twinkle little star' is a...", options: ["Story", "Poem/rhyme", "Speech", "Letter"], answer: "Poem/rhyme" },
      { q: "Star rhymes with...", options: ["Moon", "Car", "Sky", "Sun"], answer: "Car" },
    ],
    [
      { q: "Rhyming words have similar...", options: ["Spellings", "Sounds at the end", "Meanings", "Lengths"], answer: "Sounds at the end" },
      { q: "A 'verse' in a poem is like a...", options: ["Sentence", "Paragraph", "Picture", "Title"], answer: "Paragraph" },
      { q: "Most nursery rhymes have...", options: ["No rhythm", "A strong beat/rhythm", "No rhyme", "No meaning"], answer: "A strong beat/rhythm" },
      { q: "Which word rhymes with 'blue'?", options: ["Green", "Shoe", "Red", "Block"], answer: "Shoe" },
    ],
    [
      { q: "What is a 'stanza'?", options: ["A line", "A verse/paragraph in a poem", "A rhyme", "A title"], answer: "A verse/paragraph in a poem" },
      { q: "What does a poem's rhythm do?", options: ["Nothing", "Creates a beat", "Makes it longer", "Removes meaning"], answer: "Creates a beat" },
      { q: "Poetry often uses which?", options: ["Only facts", "Imagery and feelings", "Mostly numbers", "Diagrams"], answer: "Imagery and feelings" },
      { q: "'Limerick' has how many lines?", options: ["3", "4", "5", "6"], answer: "5" },
    ],
    [
      { q: "A haiku has how many lines?", options: ["2", "3", "4", "5"], answer: "3" },
      { q: "Haiku lines have syllable count:", options: ["3-5-3", "5-7-5", "7-5-7", "4-6-4"], answer: "5-7-5" },
      { q: "'Free verse' means...", options: ["No rhyme scheme", "Always rhymes", "Very short", "Very long"], answer: "No rhyme scheme" },
      { q: "What is 'repetition' in poetry?", options: ["Same words/phrases repeated", "Long lines", "Ending lines", "Rhyming"], answer: "Same words/phrases repeated" },
    ],
    [
      { q: "What is 'enjambment'?", options: ["A jam recipe", "A line running into the next", "A type of poem", "A rhyme scheme"], answer: "A line running into the next" },
      { q: "What rhyme scheme is ABAB?", options: ["Alternate rhyming", "Couplets", "Free verse", "No rhyme"], answer: "Alternate rhyming" },
      { q: "A 'couplet' is...", options: ["Two rhyming lines", "Three lines", "Four lines", "A whole poem"], answer: "Two rhyming lines" },
      { q: "What is 'meter' in poetry?", options: ["The beat pattern", "Length", "Title", "Theme"], answer: "The beat pattern" },
    ],
    [
      { q: "What is a 'sonnet'?", options: ["A 10-line poem", "A 14-line poem", "A 20-line poem", "Any poem"], answer: "A 14-line poem" },
      { q: "What is 'iambic pentameter'?", options: ["5 pairs of syllables per line", "10 rhymes", "3 stanzas", "Free verse"], answer: "5 pairs of syllables per line" },
      { q: "A 'volta' in a sonnet is...", options: ["The turn/shift in theme", "The ending", "The title", "A rhyme"], answer: "The turn/shift in theme" },
      { q: "An 'ode' is a poem that...", options: ["Mourns death", "Praises someone/something", "Tells a joke", "Describes war"], answer: "Praises someone/something" },
    ],
  ],
  "Shakespeare Intro": [
    [
      { q: "Who wrote Romeo and Juliet?", options: ["Dahl", "Shakespeare", "Rowling", "Dickens"], answer: "Shakespeare" },
      { q: "Shakespeare wrote long ago in which country?", options: ["USA", "France", "England", "Spain"], answer: "England" },
      { q: "Shakespeare wrote mostly...", options: ["Novels", "Plays", "Songs", "News"], answer: "Plays" },
      { q: "'Thou' is an old word for...", options: ["Me", "You", "He", "We"], answer: "You" },
    ],
    [
      { q: "Shakespeare's plays are performed in...", options: ["Cinemas only", "Theatres", "Bookshops", "Nowhere"], answer: "Theatres" },
      { q: "Romeo and Juliet is a love...", options: ["comedy", "tragedy", "mystery", "fairytale"], answer: "tragedy" },
      { q: "Which famous theatre is linked to Shakespeare?", options: ["The Globe", "Royal Albert", "Odeon", "Palace"], answer: "The Globe" },
      { q: "'Hath' is old English for...", options: ["Has", "Had", "Have", "Happened"], answer: "Has" },
    ],
    [
      { q: "When was Shakespeare born?", options: ["1464", "1564", "1664", "1764"], answer: "1564" },
      { q: "Where was Shakespeare from?", options: ["London", "Stratford-upon-Avon", "York", "Bath"], answer: "Stratford-upon-Avon" },
      { q: "'What light through yonder window breaks?' - from?", options: ["Hamlet", "Macbeth", "Romeo and Juliet", "Othello"], answer: "Romeo and Juliet" },
      { q: "Shakespeare's plays types include tragedy, comedy and...", options: ["History", "Musical", "Novel", "Film"], answer: "History" },
    ],
    [
      { q: "Romeo and Juliet is a...", options: ["Comedy", "History", "Tragedy", "Musical"], answer: "Tragedy" },
      { q: "What is 'thee' in modern English?", options: ["Me", "You", "He", "We"], answer: "You" },
      { q: "Macbeth's ambition leads to his...", options: ["Success", "Downfall", "Marriage", "Wealth"], answer: "Downfall" },
      { q: "In A Midsummer Night's Dream, what transforms Bottom?", options: ["A potion", "A donkey head", "A love spell", "Fairy wings"], answer: "A donkey head" },
    ],
    [
      { q: "A Midsummer Night's Dream is a...", options: ["Tragedy", "History", "Comedy", "Horror"], answer: "Comedy" },
      { q: "In Hamlet, who appears as a ghost?", options: ["A beggar", "Hamlet's father", "A farmer", "A priest"], answer: "Hamlet's father" },
      { q: "The 'three witches' appear in which play?", options: ["Hamlet", "Macbeth", "Othello", "Romeo and Juliet"], answer: "Macbeth" },
      { q: "'To be or not to be' is from...", options: ["Romeo and Juliet", "Hamlet", "Macbeth", "King Lear"], answer: "Hamlet" },
    ],
    [
      { q: "What is iambic pentameter?", options: ["A dance", "10-syllable rhythm per line", "A character", "A stage direction"], answer: "10-syllable rhythm per line" },
      { q: "What is 'dramatic irony' in Shakespeare?", options: ["Audience knows more than characters", "Comedic timing", "A tragic event", "A soliloquy"], answer: "Audience knows more than characters" },
      { q: "A 'soliloquy' is...", options: ["Group speech", "A character's private spoken thoughts", "Stage direction", "Song"], answer: "A character's private spoken thoughts" },
      { q: "Shakespeare's sonnets are typically about...", options: ["Love, time, beauty", "War only", "Politics", "Cooking"], answer: "Love, time, beauty" },
    ],
  ],
  "Essay Skills": [
    [
      { q: "A story/essay has a beginning, middle and...", options: ["Top", "End", "Side", "Cover"], answer: "End" },
      { q: "Writing needs to be...", options: ["Messy", "Clear", "Hidden", "Upside down"], answer: "Clear" },
      { q: "Each main idea should have its own...", options: ["Letter", "Paragraph", "Book", "Cover"], answer: "Paragraph" },
      { q: "Before writing, it helps to...", options: ["Just start", "Plan", "Skip it", "Copy"], answer: "Plan" },
    ],
    [
      { q: "An introduction comes at the...", options: ["End", "Beginning", "Middle", "Nowhere"], answer: "Beginning" },
      { q: "A good paragraph has...", options: ["One sentence", "One main idea", "Only facts", "Lots of ideas mixed"], answer: "One main idea" },
      { q: "The 'conclusion' is the...", options: ["Start", "End/summary", "Middle", "Title"], answer: "End/summary" },
      { q: "To join ideas, we use...", options: ["Numbers", "Connectives like 'and', 'but'", "Pictures", "Full stops only"], answer: "Connectives like 'and', 'but'" },
    ],
    [
      { q: "An essay should have...", options: ["Just a beginning", "Beginning, middle, end", "Only facts", "Only opinions"], answer: "Beginning, middle, end" },
      { q: "What does 'draft' mean?", options: ["Final copy", "Early version to edit", "The cover", "A title"], answer: "Early version to edit" },
      { q: "'Editing' means...", options: ["Writing more", "Checking and improving", "Throwing away", "Copying"], answer: "Checking and improving" },
      { q: "A 'topic' of an essay is...", options: ["What it's about", "How long it is", "The author", "The grade"], answer: "What it's about" },
    ],
    [
      { q: "What is a 'thesis statement'?", options: ["A question", "Your main argument", "The conclusion", "A quote"], answer: "Your main argument" },
      { q: "Paragraphs should have a...", options: ["Title", "Topic sentence", "Picture", "Song"], answer: "Topic sentence" },
      { q: "Evidence supports your...", options: ["Title", "Arguments/points", "Name", "Teacher"], answer: "Arguments/points" },
      { q: "Good writing uses varied...", options: ["Fonts", "Sentence structures", "Colours", "Sizes"], answer: "Sentence structures" },
    ],
    [
      { q: "A paragraph should start with...", options: ["However", "A topic sentence", "A question always", "I think"], answer: "A topic sentence" },
      { q: "What does 'counterargument' mean?", options: ["Agreeing", "The opposing view", "A maths term", "The conclusion"], answer: "The opposing view" },
      { q: "A strong intro hooks the...", options: ["Writer", "Reader", "Teacher only", "Computer"], answer: "Reader" },
      { q: "Transitional phrases help...", options: ["Confuse readers", "Connect ideas smoothly", "Shorten essays", "Add pictures"], answer: "Connect ideas smoothly" },
    ],
    [
      { q: "Formal writing avoids...", options: ["Long words", "Slang and contractions", "Facts", "Paragraphs"], answer: "Slang and contractions" },
      { q: "A strong conclusion should...", options: ["Add new points", "Summarise & reinforce thesis", "Be one word", "Copy the intro"], answer: "Summarise & reinforce thesis" },
      { q: "What is the purpose of 'analysis' in essay writing?", options: ["Describe only", "Explain how/why evidence proves the point", "Summarise", "Repeat facts"], answer: "Explain how/why evidence proves the point" },
      { q: "'Hedging language' (e.g. 'suggests') is used to...", options: ["Make claims weaker", "Show academic caution", "Confuse readers", "Shorten essays"], answer: "Show academic caution" },
    ],
  ],
};